
# GitHub Actionsワークフローファイル
# ファイル名: .github/workflows/main.yml

name: Scrape TimeTree and Update Google Calendar

on:
  # 毎日午前0時 (UTC) に自動実行
  # 日本時間の午前9時に相当します。時間は自由に変更してください。
  # 例: 日本時間の午前7時にしたい場合 -> cron: "0 22 * * *"
  schedule:
    - cron: "0 0 * * *"
  
  # GitHubのActionsタブから手動で実行することも可能にする
  workflow_dispatch:

jobs:
  scrape-and-update:
    # 実行環境として最新のUbuntuを使用
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリのコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Python環境をセットアップ
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # 使用するPythonのバージョン

      # 3. Pythonの依存ライブラリをインストール
      # (requirements.txt ファイルをリポジトリのルートに作成する必要があります)
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # 4. PlaywrightのブラウザとOS依存関係をインストール
      - name: Install Playwright browsers
        run: playwright install --with-deps

      # 5. Pythonスクリプトを実行
      # GitHub Secretsから認証情報を環境変数としてスクリプトに渡す
      - name: Run scraper script
        env:
          TIMETREE_EMAIL: ${{ secrets.TIMETREE_EMAIL }}
          TIMETREE_PASSWORD: ${{ secrets.TIMETREE_PASSWORD }}
          GAS_WEBAPP_URL: ${{ secrets.GAS_WEBAPP_URL }}
        run: python timetree_scraper.py

